'''mixup.py takes the high-confidence pseudolabelled dataset generated by create-pseudo.py
and generates a "mixed" dataset with a 50-50 split between high-confidence labelled real data
and synthetic data. The result of mixup.py can be used with augmentation to train a mixed
model which contains both synthetic and self-labelled real data
'''
import os
import shutil
import random
import tqdm

#Set root directories
pseudo_folder = 'path\to\real\images\to\be\pseudolabelled'
synth_folder = 'path\to\synth\training\data'
target_folder = 'path\to\output\folder'

#Specify/generate subdirectories for traversal
pseudo_imgs = os.path.join(pseudo_folder,'images')
pseudo_labels = os.path.join(pseudo_folder,'labels')

synth_imgs = os.path.join(synth_folder,'images')
synth_labels = os.path.join(synth_folder,'labels')

target_imgs = os.path.join(target_folder,'images')
target_labels = os.path.join(target_folder,'labels')

if not os.path.isdir(target_folder):
    os.mkdir(target_folder)
if not os.path.isdir(target_imgs):
    os.mkdir(target_imgs)
if not os.path.isdir(target_labels):
    os.mkdir(target_labels)

#perform mixup
for folder in tqdm.tqdm(os.listdir(pseudo_labels)):
    for pseudo_label in [os.path.join(pseudo_labels,folder,i) 
                for i in os.listdir(os.path.join(pseudo_labels,folder))]:
        pseudo_img = os.path.join(pseudo_imgs,pseudo_label.split('\\')[-2],pseudo_label.split('\\')[-1].split('.')[0]+'.jpg')

        synth_dirs = [os.path.join(synth_labels,i) for i in os.listdir(synth_labels) if os.path.isdir(os.path.join(synth_labels,i))]
        random_synth_dir = os.path.join(synth_labels,synth_dirs[random.randint(0,len(synth_dirs)-1)])
        synth_dir_labels = [i for i in os.listdir(random_synth_dir) if i.split('.')[-1]=='txt']
        synth_label = os.path.join(random_synth_dir,synth_dir_labels[random.randint(0,len(synth_dir_labels)-1)])
        synth_img = os.path.join(synth_imgs,synth_label.split('\\')[-2],synth_label.split('\\')[-1].split('.')[0]+'.jpg')

        target_pseudo_label = os.path.join(target_labels,'pseudo',pseudo_label.split('\\')[-2],pseudo_label.split('\\')[-1])
        target_pseudo_img = os.path.join(target_imgs,'pseudo',pseudo_img.split('\\')[-2],pseudo_img.split('\\')[-1])
        target_synth_label = os.path.join(target_labels,'synth',synth_label.split('\\')[-2],synth_label.split('\\')[-1])
        target_synth_img = os.path.join(target_imgs,'synth',synth_img.split('\\')[-2],synth_img.split('\\')[-1])
        
        os.makedirs(os.path.dirname(target_pseudo_label), exist_ok=True)
        shutil.copy(pseudo_label,target_pseudo_label)
        os.makedirs(os.path.dirname(target_pseudo_img), exist_ok=True)
        shutil.copy(pseudo_img,target_pseudo_img)
        os.makedirs(os.path.dirname(target_synth_label), exist_ok=True)
        shutil.copy(synth_label,target_synth_label)
        os.makedirs(os.path.dirname(target_synth_img), exist_ok=True)
        shutil.copy(synth_img,target_synth_img)
